### ISSUE TITLE
SNAP gate dynamical phase

### ISSUE THREAD

**Issue by vsandinh** [sequencing-dev/sequencing#25]
In the SNAP gate example, there is an amount of 2 * np.pi * n * chi * pulse_length that was added to the phases to be added by SNAP gates. Is this dynamical phase? Is it only an approximation? I tried to apply the exact same SNAP gate to a non-entangled state where the qubit is in excited state for all photon numbers but the dynamical phases seem to be slightly different from this value. Thanks!

**Comment by loganbvh** [comment]
If I remember correctly, this additional phase was found through trial and error. But it has been a long time since I've worked on this, so I could be wrong.

**Comment by vsandinh** [comment]
Thanks!
